### DISCUSSION TITLE
Lite Queen in Coolify

### DISCUSSION THREAD

**Discussion by diegogva** [kivS/lite-queen#6] [Q&A] [answered]
Hi, I installed Lite Queen in Coolify following this guide: 
https://litequeen.com/guides/how-to-use-lite-queen-on-your-server-with-coolify--one-click-install/

1. How do I upload an existing SQLite database into Coolify / Lite Queen, there is no option to select a file
2. I tried using:
labels:
      - caddy_0.basicauth.0_testuser=$2a$14$XXoxLTSzzVgMFzn.xTVMQeJzMPpnmPNvRYic4dGMeUmwiNL1y9nHq
      
As explained here: https://litequeen.com/guides/how-to-manage-sqlite-databases-on-a-linux-server-with-coolify-and-lite-queen/

But Queen Lite simply opens, never asking for any credentials. 

Here is the configuration, any suggestions on points 1 and 2? Thank you!

<img width="948" alt="Screenshot 2024-11-27 at 12 32 58" src="https://github.com/user-attachments/assets/8534e6c9-e546-4a24-abd4-a727f45b8a85">

**Comment by kivS** [comment, marked as answer]
Hey! 

1. You can just send the database files directly to your server. for example, with `scp`: 
`scp test.sqlite3 root@your-server-ip:/var/www/project1/test.sqlite3`

2. 

- If you're using the Traefik proxy(the default) the label is different, [here's the instructions from Coolify](https://coolify.io/docs/knowledge-base/traefik/basic-auth#docker-compose-and-services).

- If you're using the caddy proxy that should work: 
  - **testuser** is the username in this example
  - the rest is an hashed password in base64. you can use the `caddy hash-password` utility to get the hashed password.
  if you're using docker you can quickly run it with `docker run -it  caddy caddy hash-password`

   - for example, this should give you the auth for: testuser(username) with test(password)
  
    ```yaml
  litequeen:
    image: 'kivsegrob/lite-queen:latest'
    environment:
      - SERVICE_FQDN_LITEQUEEN_8000
    volumes:
      - 'litequeen-data:/home/litequeen/data'
      -
        type: bind
        source: /home/something/www
        target: /www
        is_directory: true
    healthcheck:
      test:
        - CMD-SHELL
        - "bash -c ':> /dev/tcp/127.0.0.1/8000' || exit 1"
      interval: 5s
      timeout: 5s
      retries: 3
    labels:
      - caddy_0.basicauth.0_testuser=$2a$14$lzgnh7rchiRBRnvZYylnvuYM4G9ShQdbvG/qj992HDO7r..R21KNu
    ```


Hope it helps, cheers.
